# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: http://mazhuang.org
url: "/"
domain: 
date_format: "ordinal"
title: 码志
subtitle: "码而立·码而生"
description: "码志|码而立·码而生"
author: Zhuang Ma 
name: Zhuang Ma 
keywords: 码志
gavatar: /favicon.ico
favicon: /favicon.ico
header-img: facebook.jpg
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/mzlogin/mzlogin.github.io

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email: chumpma@gmail.com

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: 
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - with_toc_data
        - strikethrough

pygments: true
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
duoshuo_username: mazhuang
github_username: mzlogin
douban_username: freedim
facebook_username: mzlogin
weibo_username: mzlogin
zhihu_username: mzlogin
twitter_username: mzlogin
changyan: false

# ---------------- #
#     Defaults     #
# ---------------- #
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "Zhuang Ma"
            header-img: "facebook.jpg"
            autotoc: true
    -
        scope:
            path: ""
            type: "wiki"
        values:
            autotoc: true

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM]
popular_repos: ['chinese-copywriting-guidelines','android-reverse-engineering', 'csdncommenter', 'mzlogin.github.io', 'vim-markdown-toc']
contribute_repos: ['sparanoid/chinese-copywriting-guidelines', 'waylife/RentCrawer']

