# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: http://mzlog.com
date_format: "ordinal"
title: 码志
description: "码志|码而立·码而生"
author: Zhuang Ma 
gavatar: /favicon.ico
favicon: /favicon.ico
header-img: facebook.jpg
timezone: Asia/Shanghai

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
pygments: true
paginate: 8
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-sitemap
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
duoshuo_username: mazhuang
github_username: mzlogin
douban_username: freedim
facebook_username: mzlogin
weibo_username: mzlogin
zhihu_username: mzlogin
twitter_username: mzlogin
changyan: false

# ---------------- #
#  Posts default   #
# ---------------- #
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "Zhuang Ma"
            header-img: "facebook.jpg"
